
name: Node.js CI

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - name: upload build
        run: node esbuild.mjs
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/build.zip
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update lambda with new build
        run: |
          aws lambda update-function-code \
          --function-name  ${{secrets.LAMBDA_FUNCTION_NAME}} \
          --zip-file fileb://dist/build.zip | jq '
            if .Environment.Variables? then .Environment.Variables = "{}" . end'
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
